org: herickmotta
app: minions-aws-node-rest-api-app
service: minions-aws-node-rest-api-app
frameworkVersion: '2'
package:
  individually: true
plugins:
  - serverless-dynamodb-local
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  tableName: 'minions-table-${self:provider.stage}'
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true
      inMemory: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:custom.tableName}
            sources: [src/mocks/products.json]

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  environment:
    MINIONS_TABLE: ${self:custom.tableName}

functions:
  createProduct:
    handler: src/api/product.create
    events:
      - http:
          path: products
          method: post
          cors: true
  listProducts:
    handler: src/api/product.getAll
    events:
      - http:
          path: products
          method: get
          cors: true
  createUser:
    handler: src/api/user.create
    events:
      - http:
          path: users
          method: post
          cors: true
  getUser:
    handler: src/api/user.getByEmail
    events:
      - http:
          path: users
          method: get
          cors: true
  createOrder:
    handler: src/api/order.create
    events:
      - http:
          path: orders
          method: post
          cors: true
          authorizer: aws_iam




resources:
  Resources:
    MinionsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: PK
            AttributeType: S
          -
            AttributeName: SK
            AttributeType: S
        KeySchema:
          -
            AttributeName: PK
            KeyType: HASH
          -
            AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
